name: expense_tracker
description: App to track expenses
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^9.0.0
  email_validator: ^3.0.0
  firebase_core: ^3.12.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1

  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  logging: ^1.3.0
  supabase_flutter: ^2.8.4
  uuid: ^4.2.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.2
  injectable_generator: ^2.6.2
  json_serializable: 6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  hive_ce_generator: ^1.8.1

dependency_overrides:
  source_gen: ^1.0.0
  pub_semver: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/illustrations/
    - assets/icons/
    - shorebird.yaml
    - .env
# flutter native splash screen
flutter_native_splash:
  color: "#7F3DFF"
  background_image: "assets/launcher.png"
  android: true
  ios: true
  android_12:
    image: assets/launcher.png
    icon_background_color: "#7F3DFF"
    image_dark: assets/launcher.png
    icon_background_color_dark: "#7F3DFF"

flutter_intl:
  enabled: true
