name: Build and Deploy Android to Firebase App Distribution

on:
  push:
    branches: [main, feature/setup-fastlane] # Trigger on pushes to the main branc
    tags:
      - v* # Optional: Trigger on version tags (e.g., v1.0.0)
env:
  SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Android builds)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # Use Zulu OpenJDK
          java-version: '17' # Java 11 is required for Flutter Android builds

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.0' # Replace with your Flutter version
          channel: 'stable'

      # install ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.7'
          bundler-cache: true

      # install bundle on android directory
      - name: Install dependencies
        run: |
          cd android
          bundle install

      # Set up environment variables
      - name: Set up environment variables
        env:
          ANDROID_FIREBASE_APP_ID: ${{ secrets.ANDROID_FIREBASE_APP_ID }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          echo "ANDROID_FIREBASE_APP_ID=$ANDROID_FIREBASE_APP_ID" >> $GITHUB_ENV
          echo "FIREBASE_TOKEN=$FIREBASE_TOKEN" >> $GITHUB_ENV
      
      - name: Set up Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true


      - name: Release Shorebird
        uses: shorebirdtech/shorebird-release@v1
        id: shorebird-release
        with:
          args:  --flavor=development --target=lib/main_development.dart
          flutter-version: 3.29.2
          platform: android
          working-directory: ${{ github.workspace }}/android


      # deploy using Fastlane
      - name: Run Fastlane
        run: |
          cd android
          bundle exec fastlane distribute_to_firebase

      # add testers to Firebase App Distribution
      - name: Add Testers
        run: |
          cd android
          bundle exec fastlane add_testers