name: Deploy Flutter App to Firebase App Distribution (Android)

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the master branch (or adjust to your preferred branch)

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the build environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Check out the repository to the runner

      - name: Set up Flutter
        uses: subosito/flutter-action@v2  # Set up Flutter on the runner
        with:
          flutter-version: '3.29.0' # Specify the Flutter version to use

      - name: Install dependencies
        run: flutter pub get  # Install Flutter dependencies defined in pubspec.yaml

      - name: Create google-services.json
        env:
          DATA: ${{secrets.GOOGLE_SERVICES_JSON}}  # Your base64-encoded secret
        run: |
          mkdir -p android/app
          echo "$DATA" | base64 -di > android/app/google-services.json
          
      - name: Build APK for Android
        run: flutter build apk --release  # Build the release APK for Android

      - name: Deploy to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1  # Use Firebase Distribution GitHub Action to deploy
        with:
          appId: ${{secrets.ANDROID_FIREBASE_APP_ID}}  # Firebase App ID for Android
          serviceCredentialsFileContent: ${{secrets.SERVICE_ACCOUNT_KEY}}  # Firebase service account key for authentication
          groups: testers  # Distribution group(s) to receive the app
          file: build/app/outputs/flutter-apk/app-release.apk  # Path to the built APK file